name: yomiru
description: 轻之国度 lightnovel.fun 第三方客户端(基础版)
publish_to: 'none'
version: 1.0.5+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.4.2
  cupertino_icons: ^1.0.6
  wakelock_plus: ^1.2.5
  flutter_open_chinese_convert: 0.9.0
  url_launcher: ^6.3.0
  gal: ^2.3.0
  share_plus: ^10.1.0
  package_info_plus: ^8.1.0
  device_info_plus: ^11.5.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false
